/* eslint-disable no-console */
import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { getCharacters } from "services/apis/marvel";

const Home: NextPage = () => {
  const charactes = async () => {
    try {
      const data = await getCharacters();

      return data;
    } catch (e) {
      return console.error(e);
    }
  };

  useEffect(() => {
    charactes();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
